### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by moraisaugusto** [marcosmoura/generator-scaffold#1]
I have a problem running the yo:scaffold on windows 8.1

http://jmp.sh/yCPuhez

The cmd gives me this error. I need to run manually using grunt (only).

Please, Could you fix this?

**Comment by marcosmoura** [comment]
Oh, right!
This happens because of a failure to check if the generator is running or not build. It's not a Windows related problem. Also happens in osx. I'll fix this.
